[workspace]
members = [
    "bananagraph",
    "example",
    "grid",
    "map_editor",
    "matcha",
    "roguelike", "rpg", "sevendrl",
    "text",
    "web-example"]
resolver = "2"

[profile.release]
strip = true
