[package]
name = "compute_shade"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "22.1.0"
log = "0.4.22"
bytemuck = { version = "1.17.1", features = ["derive"] }
env_logger = "0.11.5"
wasm-bindgen-futures = "0.4.43"
pollster = "0.3.0"
winit = { version = "0.29", features = ["rwh_05"] }