[package]
name = "grid"
version = "0.1.0"
edition = "2021"

[dependencies]
line_drawing = "1.0.0"
rand = { version = "0.8.5", optional = true }
cgmath = "0.18.0"

[features]
default = []
# Features that require a random number generator
rand = ["dep:rand"]
