[package]
name = "map_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-beta.1"
env_logger = "0.11.5"
bananagraph = { path = "../bananagraph" }
grid = { path = "../grid" }
winit = "0.30.9"
pollster = "0.3.0"
cgmath = "0.18.0"
